### PR TITLE
Rjenson patch 1

### PR DESCRIPTION
**Pull request by rjenson**
First pass.

### CODE REVIEW

**Comment by chadsmall** [comment]
Hmm - I'm a little worried this might overwrite some changes.  Ok if we just close this and deal with "Datica" to "Bind" changes on a per file basis?

**Comment by rjenson** [comment]
Arrgh. patch-1 was only supposed to be one file!

**Comment by chadsmall** [comment]
Whatcha think, can we start over and close this one?  Or will you loose a bunch?

**Comment by rjenson** [comment]
Let's just blow this away. And I'll re-add (and try to figure out what happened)

**Pull request closed without merging**
